### ISSUE TITLE
Change the design of the current day to the menstrual phase

### ISSUE THREAD

**Issue by IraSoro** [IraSoro/peri#217]
Now the desing of the current day to the menstrual phase looks like this (dark theme):
![Image](https://github.com/IraSoro/peri/assets/52165881/47c683c3-f87b-4f4b-a020-7eb7ffc5501e)
light theme:
![Image](https://github.com/IraSoro/peri/assets/52165881/36e085fe-adfc-4378-9565-37d3a1565c2d)

You need to change this design.

**Comment by imblowfish** [comment]
What's wrong with the current design?
It's hard to see the current day on the dark theme or anything else?
