### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by CyberSymptom** [IraSoro/peri#227]
Hello, i am new here, Your Peri app is flutter code ? 
if these code in flutter can you give me this app flutter code please ?

**Comment by imblowfish** [comment]
Hello @CyberSymptom
We don't use Flutter and instead we use Ionic framework with React. If you never heard about Ionic framework you can find all details here on official page https://ionicframework.com/.

If you interested in peri app code you can find it in this repo's code section or use `git clone` to read code locally like with any other repository on Github. More info here https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository

**Comment by IraSoro** [comment]
Hello @CyberSymptom! Thank you for your interest in our project. 
The Peri app is developed using Ionic and React. But I used to develop a period tracker using Flutter. This is an old project, but, if you want, you can see it https://github.com/IraSoro/period-tracker.
