### ISSUE TITLE
Hacktoberfest: Add translation

### ISSUE THREAD

**Issue by IraSoro** [IraSoro/peri#279]
We are looking for contributions to translate our app into different languages! 

#### How to Contribute:
1. **Create a Pull Request**:
If you'd like to contribute a translation, you can find complete instructions in [CONTRIBUTING.md](https://github.com/IraSoro/peri/blob/master/CONTRIBUTING.md) file.

2. **Discussion Option**:
Alternatively, if you prefer to share your translation without creating a Pull Request, you can simply attach your translated file or leave a comment with your translation in the dedicated [discussion](https://github.com/IraSoro/peri/discussions/284).

#### Example File:
For reference, here’s an example of a translated file into [Russian](https://github.com/IraSoro/peri/blob/master/src/utils/translations/ru.ts) and [Spanish](https://github.com/IraSoro/peri/blob/master/src/utils/translations/es.ts).

#### Existing Translations:
We currently have translations stored in the [translations](https://github.com/IraSoro/peri/tree/master/src/utils/translations) folder. Feel free to check them out for consistency.

#### Important Notes:
Your contributions can be counted towards Hacktoberfest if you submit your translation through a Pull Request or by sharing it in the discussion.

Thank you for your help in making our project accessible to more users!

**Comment by SourabhRajput123** [comment]
I apologize for submitting a pull request without being formally assigned to the task. I found the changes straightforward and proceeded to implement them based on your instructions. I have adhered to all guidelines and have only added new code without removing any lines from the original code. I would appreciate it if you could review my changes, and I welcome any feedback you may have.

**Comment by deatheguard** [comment]
Hey! Just wanted to let you know that I looked through the French translation and made a couple of corrections - they are in my pull request. Hope this helps!

**Comment by imblowfish** [comment]
Hey @deatheguard
Thank you very much!
@IraSoro and I will look your PR as soon as possible

**Comment by Darpana-iitgn** [comment]
Can we translate in any language we are proficient in? I know English, Hindi and Gujarati. This has a hinglish translation (not 100% hindi language) and no gujarati translation.
