### ISSUE TITLE
Request to add specific LICENSE

### ISSUE THREAD

**Issue by IntegerAlex** [IraSoro/peri#290]
Is your feature request related to a problem? Please describe.
I often face challenges when forking projects because I need to determine the licensing and intellectual property information before proceeding. Without clear and accessible licensing details, it can be difficult to know what I am permitted to do with the code.

Describe the solution you'd like I would like to see,
 A dedicated licensing section in project repositories that clearly states the licensing information (e.g., GPLv3 or 2-Clause BSD). This section should include a brief summary of the key aspects of each license, outlining the rights and obligations for users.

Describe alternatives you've considered Currently, 
I manually check the README or look for license files, but this is often cumbersome and not always effective. A dedicated licensing section would simplify this process and improve clarity.

Additional context,
Having a well-defined licensing section would enhance the user experience, ensuring compliance with licensing terms. This is particularly important for projects using GPLv3 or 2-Clause BSD, as users need to understand the implications of each license type.

Assign me if you want to add this feature!

**Comment by IntegerAlex** [comment]
So technically currently project is Source-Open  not Open-source. 
If you want to retain more rights BSD-3 would go Appropriate or SSPL.

**Comment by IraSoro** [comment]
> So technically currently project is Source-Open not Open-source. If you want to retain more rights BSD-3 would go Appropriate or SSPL.

Technically, yes. 
We haven't yet decided on a license, as we are not sure about further development plans and interaction with the community. But we know for sure that the project will remain open.
