### ISSUE TITLE
Want to make the dropdown icon working 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [IraSoro/peri#291]
**Is your feature request related to a problem? Please describe.**
When i am clicking on the dropdown icon then it is not working 
It have to show the next months so that i can directly select the month from their 

**Describe the solution you'd like**
I will add the feature to add the further months 

https://github.com/user-attachments/assets/d395ee92-77d1-493e-ac4b-daa5cffeb8d2

**Comment by IraSoro** [comment]
Hello, @Ayushmaanagarwal1211! Thank you for your interest in our project.

Yes, the problem you described exists. You can read more about it in this PR #190 . There we explained why this bug exists.

Our project is made with React and [Ionic](https://ionicframework.com/).  Ionic provides an [Ionic UI Kit](https://ionicframework.com/docs/components). At the moment, the bug described in the PR #190 has not been solved.

If you have any ideas on how to fix this, feel free to write!
