### ISSUE TITLE
Period Tracker allows setting period dates without any limits

### ISSUE THREAD

**Issue by Piyush-linux** [IraSoro/peri#303]
**Describe the bug**
Enter unrealistic cycle lengths

**Peri App Version**
v2.4.2

**To Reproduce**
1. Go to Home Screen
2. Pick a date as many as you like 

**Expected behavior**
Proper validation

**Screenshots**
![Screenshot_2024-10-05-12-43-54_1920x1080](https://github.com/user-attachments/assets/d092185c-514a-4909-844b-1682810a66c3)

**Additional Context**
> If anything comes across as insensitive, I sincerely apologize

**Comment by IraSoro** [comment]
Hello, @Piyush-linux! Thank you for your interest in the project!

The bug you described exists. We can't fix it at the moment, but we know that such a bug exists. We are thinking about how to fix it in the future. Perhaps we will change the calendar or write our own that will meet our needs. If you have any ideas - write!

Thanks for paying attention to this!

**Comment by Piyush-linux** [comment]
I'll try to find a Calender UI Component too !
