### ISSUE TITLE
Hacktoberfest: Add translation

### ISSUE THREAD

**Issue by IraSoro** [IraSoro/peri#308]
We are looking for contributions to translate our app into different languages! 

#### How to Contribute:
1. **Create a Pull Request**:
If you'd like to contribute a translation, you can find complete instructions in [CONTRIBUTING.md](https://github.com/IraSoro/peri/blob/master/CONTRIBUTING.md) file.

2. **Discussion Option**:
Alternatively, if you prefer to share your translation without creating a Pull Request, you can simply attach your translated file or leave a comment with your translation in the dedicated [discussion](https://github.com/IraSoro/peri/discussions/284).

#### Example File:
For reference, here’s an example of a translated file into [Russian](https://github.com/IraSoro/peri/blob/master/src/utils/translations/ru.ts) and [French](https://github.com/IraSoro/peri/blob/master/src/utils/translations/fr.ts).

#### Existing Translations:
We currently have translations stored in the [translations](https://github.com/IraSoro/peri/tree/master/src/utils/translations) folder. Feel free to check them out for consistency.

#### Important Notes:
Your contributions can be counted towards Hacktoberfest if you submit your translation through a Pull Request or by sharing it in the discussion.

Thank you for your help in making our project accessible to more users!

**Comment by taib2111862** [comment]
Hello @IraSoro 
I've seen your project and I have worked on adding Vietnamese. Unfortunately, this issue is closed.
I finished testing the translation and it works okay although there are several terms that I'm not really sure. Can you re-open it once again so that I can contribute to your project?
Thank you for reading my comment.
Tai.

**Comment by IraSoro** [comment]
> Hello @IraSoro 
> I've seen your project and I have worked on adding Vietnamese. Unfortunately, this issue is closed.
> I finished testing the translation and it works okay although there are several terms that I'm not really sure. Can you re-open it once again so that I can contribute to your project?
> Thank you for reading my comment.
> Tai.

Hello, you can contribute without issue, just write "Added Vietnamese language" in PR title or something like that and we'll review it and merge in case of everything is ok
This issue was created for Hacktoberfest and we don't need it anymore

**Comment by taib2111862** [comment]
Thank you for your reply
