### ISSUE TITLE
 Month And Year area  seems Like A Dropdown But I cant Able To change That 

### ISSUE THREAD

**Issue by tamil752002** [IraSoro/peri#315]
![Peri Bug](https://github.com/user-attachments/assets/5a47237e-bcc3-48f3-83cb-270e06276458)
 
this is where I telling ,It seems to be Dropdown For Month and year

**Comment by IraSoro** [comment]
Hello, @tamil752002! Thank you for your interest in our project.

Yes, the problem you described exists. You can read more about it in this PR #190 . There we explained why this bug exists.

Our project is made with React and [Ionic](https://ionicframework.com/).  Ionic provides an [Ionic UI Kit](https://ionicframework.com/docs/components). At the moment, the bug described in the PR #190 has not been solved.

If you have any ideas on how to fix this, feel free to write!
