### ISSUE TITLE
Translation to tamil language 

### ISSUE THREAD

**Issue by tamil752002** [IraSoro/peri#316]
Tamil language Is the One Of the Oldest Language In the world , it would be Great , If You Add That In Your Application

**Comment by IraSoro** [comment]
Hello, @tamil752002! Thank you for your interest in the project! 
Yes, of course, you can add translation to Tamil language. You can find detailed instructions on how to submit a translation using a Pull Request in the [CONTRIBUTING.md](https://github.com/IraSoro/peri/blob/master/CONTRIBUTING.md) file.

**Comment by tamil752002** [comment]
Sorry for the mistake I made. I will do it properly next time  ,
