### ISSUE TITLE
Latest release breaks app

### ISSUE THREAD

**Issue by imblowfish** [IraSoro/peri#46]
After installation of the latest version 2.0.2 app shows incorrect data (35 days of cycle, NaN in several fields etc.)

To fix it I cleared cache and all storage data and setup app again

**Comment by IraSoro** [comment]
Sorry dear user for the inconvenience! I hope this doesn't ruin the experience of my app! I promise this won't happen again. I look forward to further cooperation.

**Comment by imblowfish** [comment]
No problem, thank you very much
