### ISSUE TITLE
Implement import/export of user config

### ISSUE THREAD

**Issue by IraSoro** [IraSoro/peri#60]
Now user config with all cycles are exists only in the app's storage and we can't move it between devices

There should be possibility to export and import config from one device to another

Config format should have version field which describes current storage data version

**Comment by imblowfish** [comment]
There are the problem with file downloading on Android 12+. Previously, developer could save file in Documents or External Storage, but not now. Now you just able to create file in cache

I tried various approaches, such as `@capacitor/filesystem` to save file in Documents/Downloads or External Storage, `@capacitor/browser` to open file which saved in cache and nothing works

But after this I decided to replace `export` logic with `share` logic and found that `@ionic/share` works fine and I able to share my config from cache and send with some image
