### ISSUE TITLE
Write a new algorithm for calculating averages

### ISSUE THREAD

**Issue by IraSoro** [IraSoro/peri#86]
Rewrite the ```getAverageLengthOfPeriod``` and ```getAverageLengthOfCycle``` functions in the ```CalculationLogics.tsx``` file.

**Comment by imblowfish** [comment]
I can't see any possibility to simplify current logic unless we get rid of storing the unfinished cycle as `0` in the index of the loops array

**Comment by IraSoro** [comment]
Agree
